#!/bin/bash

dHL=$(xdpyinfo | grep dimensions | awk '{print $2}' | sed -e "s/x/ /" | awk '{print $1}')
dVL=$(xdpyinfo | grep dimensions | awk '{print $2}' | sed -e "s/x/ /" | awk '{print $2}')
mHL=$((dHL/3))
mVL=$((dVL/11*5))

i=0
for img in "$@"; do
   x=$((i%3*mHL))
   [[ i -le 2 ]] && y=0
   [[ i -gt 2 ]] && y=$((mVL*7/6))
   mrview $img \
   -focus false \
   -noannotations \
   -sync.focus \
   -plane 2 \
   -position $x,$y \
   -size $mHL,$mVL \
   -fov 280 \
   -intensity_range 0,1200 &
   sleep 0.5
   i=$((i+1))
   [[ i -ge $# ]] && exit 0
done
